project:
  type: website
  output-dir: docs
  render:
  - index.qmd
  - programme.qmd
  - tutorials.qmd
  - organisers.qmd
  - venue-travel.qmd
  - keynotes.qmd
website:
  title: EnviBayes/INLA workshop
  navbar:
    logo: images/EnviBayes-INLA_workshop_logo.png
    left:
    - text: Home
      menu:
      - text: Submission
        href: index.html#submission
      - text: Registration
        href: index.html#regis
      - text: Important Dates 
        href: index.html#dates
      # - text: Keynote Speakers
      #   href: keynotes.qmd
  
  
    - text: Programme & Awards
      href: programme.qmd
    - text: Keynote Speakers
      href: keynotes.qmd
    - text: Tutorials
      href: tutorials.qmd
    - text: Venue & Travel
      href: venue-travel.qmd
    - text: Organisers
      href: organisers.qmd
format:
  html:
    theme: flatly
    respect-user-color-scheme: false
    toc: true
    toc-location: right
    toc-depth: 3
    css: styles.css   
execute:
  freeze: auto
